Add support for custom fingerprint
honeybadger-io/honeybadger-java pull request #433
Opened 2023-01-19 15:19 UTC by MaximeAnsquer

2023-01-20 11:30 UTC, subzero10 requested changes
Looks good! Just missing a few things.

2023-01-20 11:30 UTC, subzero10 commented on honeybadger-java/src/main/java/io/honeybadger/reporter/HoneybadgerReporter.java
>              NoticeDetails noticeDetails = new NoticeDetails(getConfig(), error, tags);
You should pass the `fingerprint` param here as well.

2023-01-20 11:30 UTC, subzero10 commented on honeybadger-java/src/main/java/io/honeybadger/reporter/dto/NoticeDetails.java
> +    private final String fingerprint;
Can you please add `fingerprint` in the `@JsonPropertyOrder` annotation on Line 19 (just for consistency)?

2023-01-20 11:30 UTC, subzero10 commented on honeybadger-java/src/main/java/io/honeybadger/reporter/dto/NoticeDetails.java
>      @Override
The `fingerprint` field is missing from the `equals` and `hashCode` methods.

2023-01-20 16:14 UTC, MaximeAnsquer commented
> Looks good! Just missing a few things.

Right I went a bit too fast, here you go [7383203](https://github.com/honeybadger-io/honeybadger-java/pull/433/commits/7383203582a7896c56edb9e91be08320b05bbc3e)

2023-01-27 09:35 UTC, subzero10 approved these changes

2023-01-27 09:36 UTC, merged

2023-02-02 07:27 UTC, MaximeAnsquer commented
@subzero10 any planned date for the release? Thanks. 🤓

2023-02-02 07:31 UTC, subzero10 commented
Hello @MaximeAnsquer, our release process is quite lengthy and manual, so I'm working on automating it. I should be done before the end of this week. If not, I will release manually and ping you!

2023-02-08 18:53 UTC, joshuap commented
2.1.1 has been released. Can you try it out and let us know if it works for you?

2023-02-09 09:00 UTC, MaximeAnsquer commented
@joshuap I'm afraid I've introduced a bug.   
When reporting an error, if the `request` parameter is `null` then the reported `message` will always be `null`.
In HoneybadgerReporter.java line 277, I passed `message = null` in the `NoticeDetails` constructor but I should have passed `reportedMessage` or `error.getMessage()`, I'm not sure which one. `reportedMessage` would make more sense to me but it would not be strictly equivalent to what it was before.   
I can submit a PR to fix the bug if you can help me decide on the solution.
Sorry!

2023-02-10 07:51 UTC, subzero10 commented
> @joshuap I'm afraid I've introduced a bug. When reporting an error, if the `request` parameter is `null` then the reported `message` will always be `null`. In HoneybadgerReporter.java line 277, I passed `message = null` in the `NoticeDetails` constructor but I should have passed `reportedMessage` or `error.getMessage()`, I'm not sure which one. `reportedMessage` would make more sense to me but it would not be strictly equivalent to what it was before. I can submit a PR to fix the bug if you can help me decide on the solution. Sorry!

Hey @MaximeAnsquer, no need to apologise! It was a mistake on my side as well that I didn't see it while reviewing :).
I will fix this and release a new version today!